print("This tool will get you the greatest of three numbers")
num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))
num3 = int(input("Enter third number: "))
greatest = max(num1, num2, num3)
print("The greatest number is " + str(greatest))
